import { StackNavigationProp } from '@react-navigation/stack';
import { RouteProp } from '@react-navigation/native';

export type RootStackParamList = {
  MainTabs: undefined;
  Login: undefined;
  Signup: undefined;
  Home: undefined;
  Profile: undefined;
  Settings: undefined;
  Help: undefined;
  Chatbot: { initialPrompt?: string } | undefined;
  Ticklist: undefined;
  Library: undefined;
  QuizSession: undefined;
  Schedule: undefined;
  LearningZone: undefined;
  CodingHub: undefined;
  GroupStudy: undefined;
  GPACalculator: undefined;
  SyllabusViewer: undefined;
  PYP: undefined;
  Explore: undefined;
};

export type LoginScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Login'>;
export type SignupScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Signup'>;
export type HomeScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Home'>;
export type ProfileScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Profile'>;
export type SettingsScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Settings'>;
export type HelpScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Help'>;
export type ChatbotScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Chatbot'>;
export type TicklistScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Ticklist'>;
export type LibraryScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Library'>;
export type QuizSessionScreenNavigationProp = StackNavigationProp<RootStackParamList, 'QuizSession'>;
export type ScheduleScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Schedule'>;
export type LearningZoneScreenNavigationProp = StackNavigationProp<RootStackParamList, 'LearningZone'>;
export type CodingHubScreenNavigationProp = StackNavigationProp<RootStackParamList, 'CodingHub'>;
export type GroupStudyScreenNavigationProp = StackNavigationProp<RootStackParamList, 'GroupStudy'>;
export type GPACalculatorScreenNavigationProp = StackNavigationProp<RootStackParamList, 'GPACalculator'>;
export type SyllabusViewerScreenNavigationProp = StackNavigationProp<RootStackParamList, 'SyllabusViewer'>;
export type PYPScreenNavigationProp = StackNavigationProp<RootStackParamList, 'PYP'>;
export type ExploreScreenNavigationProp = StackNavigationProp<RootStackParamList, 'Explore'>;

export type LoginScreenRouteProp = RouteProp<RootStackParamList, 'Login'>;
export type SignupScreenRouteProp = RouteProp<RootStackParamList, 'Signup'>;
export type HomeScreenRouteProp = RouteProp<RootStackParamList, 'Home'>;
export type ProfileScreenRouteProp = RouteProp<RootStackParamList, 'Profile'>;
export type SettingsScreenRouteProp = RouteProp<RootStackParamList, 'Settings'>;
export type HelpScreenRouteProp = RouteProp<RootStackParamList, 'Help'>;
export type ChatbotScreenRouteProp = RouteProp<RootStackParamList, 'Chatbot'>;
export type TicklistScreenRouteProp = RouteProp<RootStackParamList, 'Ticklist'>;
export type LibraryScreenRouteProp = RouteProp<RootStackParamList, 'Library'>;
export type QuizSessionScreenRouteProp = RouteProp<RootStackParamList, 'QuizSession'>;
export type ScheduleScreenRouteProp = RouteProp<RootStackParamList, 'Schedule'>;
export type LearningZoneScreenRouteProp = RouteProp<RootStackParamList, 'LearningZone'>;
export type CodingHubScreenRouteProp = RouteProp<RootStackParamList, 'CodingHub'>;
export type GroupStudyScreenRouteProp = RouteProp<RootStackParamList, 'GroupStudy'>;
export type GPACalculatorScreenRouteProp = RouteProp<RootStackParamList, 'GPACalculator'>;
export type SyllabusViewerScreenRouteProp = RouteProp<RootStackParamList, 'SyllabusViewer'>;
export type PYPScreenRouteProp = RouteProp<RootStackParamList, 'PYP'>;
export type ExploreScreenRouteProp = RouteProp<RootStackParamList, 'Explore'>;
